version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run: npm install -g firebase-tools
      - run: firebase deploy --token $FIREBASE_TOKEN

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
