version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run build  # Si usas React, Vue, etc.
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Instalar Firebase CLI
          command: npm install -g firebase-tools
      - run:
          name: Desplegar a Firebase
          command: firebase deploy --token $FIREBASE_TOKEN

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
