version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11  # Imagen oficial de CircleCI con Python
    steps:
      - checkout  # Clona tu repo

      - run:
          name: Instalar dependencias
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Ejecutar tests
          command: pytest

workflows:
  version: 2
  test-workflow:
    jobs:
      - test