version: 2.1  # is the latest CircleCI version

orbs:
  python: circleci/python@3.1.0 # orb contains a set of prepackaged CircleCI configurations you can use to do common CircleCI tasks for the Python programming language.
  slack: circleci/slack@5.1.1

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default # use the defaul executor defined within the orb
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run test
          command: |
            python -m pytest
            RESULT=$?
              if [ $RESULT -eq 0 ]; then
                STATUS="✅ Tests pasaron correctamente"
              else
                STATUS="❌ Tests fallaron"
              fi
              curl -X POST -H 'Content-type: application/json' \
                --data "{\"text\":\"$STATUS en el proyecto *$CIRCLE_PROJECT_REPONAME* (branch: $CIRCLE_BRANCH)\"}" \
                $SLACK_WEBHOOK_URL
              exit $RESULT  # devolver el estado correcto a CircleCI
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  preview_deployment:
    docker:
      - image: cimg/node:24.1.0
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest
      - run:
          name: Install Python 3.12
          command: |
            sudo apt-get update
            sudo apt-get install -y python3.12 python3.12-venv python3-pip
      
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
      - run:
          name: Build Project Artifacts
          command: vercel build --token=$VERCEL_TOKEN
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prebuilt --token=$VERCEL_TOKEN

  production_deployment:
    docker:
      - image: cimg/node:24.1.0
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest

      - run:
          name: Install Python 3.12
          command: |
            sudo apt-get update
            sudo apt-get install -y python3.12 python3.12-venv python3-pip
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
      - run:
          name: Build Project Artifacts
          command: vercel build --prod --token=$VERCEL_TOKEN
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

workflows:
  version: 2
  build_test:
    jobs:
      - build_and_test
      - preview_deployment: #The preview_deployment job will run when your code is pushed to a git branch other than main
          requires: 
            - build_and_test
          filters:
            branches:
              ignore: /main/
      - production_deployment: #the production_deployment job will run when code is merged into the main branch.
          requires: 
            - build_and_test
          filters:
            branches:
              only: /main/