version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11  # Imagen oficial de CircleCI con Python
    strategy:
      matrix:
        python-version: [3.12, 3.13]
    steps:
      - checkout  # Clona tu repo
      - run:
          name: Instalar dependencias
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Ejecutar tests
          command: |
            pytest
            RESULT=$?
              if [ $RESULT -eq 0 ]; then
                STATUS="✅ Tests pasaron correctamente"
              else
                STATUS="❌ Tests fallaron"
              fi
              curl -X POST -H 'Content-type: application/json' \
                --data "{\"text\":\"$STATUS en el proyecto *$CIRCLE_PROJECT_REPONAME* (branch: $CIRCLE_BRANCH)\"}" \
                $SLACK_WEBHOOK_URL
              exit $RESULT  # devolver el estado correcto a CircleCI

  deploy_staging:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run: npm install -g firebase-tools
      - run: firebase deploy --project staging --token $FIREBASE_TOKEN

workflows:
  version: 2
  test-workflow:
    jobs:
      - test