version: 2.1  # is the latest CircleCI version

orbs:
  slack: circleci/slack@5.1.1

jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout # checkout source code
      - run:
          name: Instalar dependencias
          command: npm install

      - run:
          name: Ejecutar test
          command: |
            set +e
            npm test
            RESULT=$?
            set -e
            if [ $RESULT -eq 0 ]; then
              STATUS="✅ Tests pasaron correctamente"
            else
              STATUS="❌ Tests fallaron"
            fi
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"$STATUS en el proyecto *$CIRCLE_PROJECT_REPONAME* (branch: $CIRCLE_BRANCH)\"}" \
              $SLACK_WEBHOOK_URL
            exit $RESULT  # devolver el estado correcto a CircleCI

  deploy:
    docker:
      - image: cimg/node:24.1.0
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest
      - run:
          name: Desplegar a Vercel
          command: vercel --prod --token=$VERCEL_TOKEN

  update-trello-card:
      docker:
        - image: cimg/base:2023.03 # Una imagen base con curl y git
      steps:
        - checkout # Clona tu repositorio para acceder al script
        - run:
            name: Ejecutar script de Trello
            command: |
              chmod +x ./update_trello_card.sh # Asegura que el script sea ejecutable
              ./update_trello_card.sh

workflows:
  version: 2
  build_test:
    jobs:
      - build_and_test
      - deploy:
          requires: 
            - build_and_test
          filters:
            branches:
              only: /main/
      - update-trello-card:
          requires: 
            - build_and_test
            - deploy