version: 2.1

orbs:
  slack: circleci/slack@5.1.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: npm install

      - run:
          name: Ejecutar test
          command: |
            set +e
            npm test
            RESULT=$?
            set -e
            if [ $RESULT -eq 0 ]; then
              STATUS="✅ Los tests pasaron correctamente"
            else
              STATUS="❌ Los tests fallaron"
            fi
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"$STATUS en el proyecto *$CIRCLE_PROJECT_REPONAME* (branch: $CIRCLE_BRANCH)\"}" \
              $SLACK_WEBHOOK_URL
            exit $RESULT  # devolver el estado correcto a CircleCI

  deploy:
    docker:
      - image: cimg/node:24.1.0
    steps:
      - checkout
      - run:
          name: Instalar Vercel CLI
          command: sudo npm install --global vercel@latest
      - run:
          name: Desplegar a Vercel
          command: vercel --prod --token=$VERCEL_TOKEN

  update-trello-card:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Instalar jq
          command: |
            sudo apt-get update
            sudo apt-get install -y jq
      - run:
          name: Mover tarjeta de Trello a completados
          command: |
            chmod +x ./update_trello_card.sh
            ./update_trello_card.sh

workflows:
  version: 2
  build_test:
    jobs:
      - build_and_test
      - deploy:
          requires: 
            - build_and_test
          filters:
            branches:
              only: /main/
      - update-trello-card:
          requires: 
            - build_and_test
            - deploy