version: 2.1  # is the latest CircleCI version

orbs:
  python: circleci/python@3.1.0 # orb contains a set of prepackaged CircleCI configurations you can use to do common CircleCI tasks for the Python programming language.
  slack: circleci/slack@5.1.1

jobs:
  build_and_test: # this can be any name you choose
  executor: python/default # use the defaul executor defined within the orb
  steps:
    - checkout # checkout source code
    - python/install-packages:
      pkg-manager: pip
    - run:
      name: Run test
      command: python -m pytest
    - persist_to_workspace:
      root: ~/project
      paths:
        - .

  notify:
    docker:
      - image: cimg/base:current
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1


workflows:
  build_test:
    jobs:
      - build_and_test
  send-notification:
    jobs:
      - notify:
          context: slack_secrets