version: 2.1  # is the latest CircleCI version

orbs:
  slack: circleci/slack@5.1.1

jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout # checkout source code
      - run:
          name: Instalar dependencias
          command: npm install

      - run:
          name: Ejecutar test
          command: |
            npm test
            RESULT=$?
              if [ $RESULT -eq 0 ]; then
                STATUS="✅ Tests pasaron correctamente"
              else
                STATUS="❌ Tests fallaron"
              fi
              curl -X POST -H 'Content-type: application/json' \
                --data "{\"text\":\"$STATUS en el proyecto *$CIRCLE_PROJECT_REPONAME* (branch: $CIRCLE_BRANCH)\"}" \
                $SLACK_WEBHOOK_URL
              exit $RESULT  # devolver el estado correcto a CircleCI

  deploy:
    docker:
      - image: cimg/node:24.1.0
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest
      - run:
          name: Autenticarse en Vercel
          command: echo "$VERCEL_TOKEN" | vercel login --token
      - run:
          name: Desplegar a Vercel
          command: vercel --prod --token $VERCEL_TOKEN

workflows:
  version: 2
  build_test:
    jobs:
      - build_and_test
      - deploy:
          requires: 
            - build_and_test
          filters:
            branches:
              only: /main/