name: Mover Tarjeta Trello por Commit

on:
  push:
    branches:
      - main # O la rama que uses como principal, por ejemplo 'master' o 'develop'

jobs:
  move-trello-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para obtener el historial completo del commit message

      - name: Mover tarjeta de Trello a "Completado"
        command: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Último commit: $COMMIT_MSG"

          # Buscar ID de tarjeta (ej: TRELLO-abc123)
          CARD_ID=$(echo "$COMMIT_MSG" | grep -oE 'TRELLO-[a-zA-Z0-9]+')

          if [ -n "$CARD_ID" ]; then
            echo "Encontrado ID de tarjeta: $CARD_ID"

            # **Paso 1: Realizar la llamada a la API de Trello**
            CARD_JSON=$(curl -s \
              "https://api.trello.com/1/search?query=$CARD_ID&key=$TRELLO_API_KEY&token=$TRELLO_TOKEN&modelTypes=cards&cards_limit=1")

            # **Paso 2: Depurar la salida de CURL (MUY IMPORTANTE para identificar el problema)**
            echo "--- DEBUG: Contenido recibido de la API de Trello ---"
            echo "$CARD_JSON"
            echo "----------------------------------------------------"

            # **Paso 3: Validar que la salida de curl es JSON válido antes de pasarlo a jq**
            if ! echo "$CARD_JSON" | jq . > /dev/null 2>&1; then
              echo "❌ ERROR: La respuesta de la API de Trello NO es un JSON válido."
              echo "Por favor, verifica:"
              echo "  1. Tus variables TRELLO_API_KEY y TRELLO_TOKEN (en los secretos de GitHub Actions)."
              echo "  2. Que el ID de tarjeta '$CARD_ID' realmente exista en Trello y sea accesible con tu token."
              echo "  3. Posibles límites de tasa de la API de Trello."
              exit 1 # Termina la acción con un error
            fi

            # **Paso 4: Extraer el ID de la tarjeta real si el JSON es válido**
            CARD_REAL_ID=$(echo "$CARD_JSON" | jq -r '.cards[0].id')

            # **Paso 5: Continuar con la lógica si se encontró un ID real**
            if [ "$CARD_REAL_ID" != "null" ]; then
              echo "Moviendo tarjeta Trello ID real: $CARD_REAL_ID (original: $CARD_ID) a lista Completado..."
              curl -X PUT "https://api.trello.com/1/cards/$CARD_REAL_ID" \
                -d "idList=$TRELLO_DONE_LIST_ID" \
                -d "key=$TRELLO_API_KEY" \
                -d "token=$TRELLO_TOKEN"
              echo "✅ Tarjeta movida exitosamente (o intento de mover)."
            else
              echo "❌ No se pudo encontrar un ID de tarjeta válido en la respuesta JSON (CARD_REAL_ID es 'null')."
              echo "Esto puede ocurrir si la tarjeta '$CARD_ID' no existe, está archivada, o no se encontró en la búsqueda."
              exit 1 # Termina la acción con un error si la tarjeta no se encontró
            fi
          else
            echo "⚠️ No se encontró ningún ID de tarjeta Trello (ej. TRELLO-abc123) en el mensaje del commit."
            echo "Este paso se saltará."
          fi
